#!/bin/bash
set -e

cp english.html build/english.html
cp index.html build/index.html
cp favicon.ico build/favicon.ico
cp -R img/ build/img/

s3cmd sync --recursive build/ s3://vivi.dentist --no-check-certificate
echo -e "\t Successfully deployed to S3"
